# Compose file for local dev, not for prod

version: '2'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: [npm, run, dev]
    environment:
      - DATABASE_URL=postgres://raidbot:raidbot@database/raidbot
    ports:
      - "9000:80"
    volumes:
      - ./src:/app/src
    links:
      - database

  database:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_DB=raidbot
      - POSTGRES_USER=raidbot
      - POSTGRES_PASSWORD=raidbot
    ports:
      - "4432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
